<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Buka_halaman_pesan_ListButton</name>
   <tag></tag>
   <elementGuidId>96e6e585-058f-423a-a615-56b854c2437f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;v__chat-dock&quot;]/div/div/div[2]/div/div[1]/div[2]/div/div[2]/span/div/div[2]/div/ul/a[1]/li/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
