<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Joemen_Verify</name>
   <tag></tag>
   <elementGuidId>83fdc6dd-9239-478d-9ea3-ecfce4719f40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;v__chat-center&quot;]/div/div[2]/div[2]/div/div[1]/div/div/div[1]/span/div/div/div[2]/div[1]/div/div[1]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
