<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pencarian_tidak_ditemukan_Verify</name>
   <tag></tag>
   <elementGuidId>be16885f-c526-4af4-9dff-cdfdbdcb6b69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;v__chat-center&quot;]/div/div[2]/div[1]/div/div[2]/div/div/p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
